/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdministrationRouteImport } from './routes/administration'
import { Route as AssetDefinitionRouteImport } from './routes/asset-definition'
import { Route as AssetDefinitionsRouteImport } from './routes/asset-definitions'
import { Route as DesignCasesRouteImport } from './routes/design-cases'
import { Route as EngineeringRouteImport } from './routes/engineering'
import { Route as ExceptionsRouteImport } from './routes/exceptions'
import { Route as ReliabilityRouteImport } from './routes/reliability'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as TroubleshootingRouteImport } from './routes/troubleshooting'
import { Route as WorkbenchRouteImport } from './routes/workbench'
import { Route as EngineeringIndexRouteImport } from './routes/engineering.index'
import { Route as EngineeringCatalogRouteImport } from './routes/engineering.catalog'
import { Route as EngineeringDesignCasesRouteImport } from './routes/engineering.design-cases'
import { Route as EngineeringGovernanceRouteImport } from './routes/engineering.governance'
import { Route as EngineeringInstallationsRouteImport } from './routes/engineering.installations'
import { Route as EngineeringWorkbenchRouteImport } from './routes/engineering.workbench'
import { Route as WellsIndexRouteImport } from './routes/wells.index'
import { Route as WellsWellIdRouteImport } from './routes/wells.$wellId'
import { Route as EngineeringCatalogIndexRouteImport } from './routes/engineering.catalog.index'
import { Route as EngineeringDefinitionIndexRouteImport } from './routes/engineering.definition.index'
import { Route as EngineeringDefinitionWellIdRouteImport } from './routes/engineering.definition.$wellId'
import { Route as EngineeringGovernanceIndexRouteImport } from './routes/engineering.governance.index'
import { Route as EngineeringGovernanceImportRouteImport } from './routes/engineering.governance.import'
import { Route as EngineeringGovernanceQualityRouteImport } from './routes/engineering.governance.quality'
import { Route as EngineeringGovernanceSourcesRouteImport } from './routes/engineering.governance.sources'
import { Route as EngineeringGovernanceValidationRouteImport } from './routes/engineering.governance.validation'
import { Route as EngineeringInstallationsIndexRouteImport } from './routes/engineering.installations.index'
import { Route as EngineeringInstallationsSystemIdRouteImport } from './routes/engineering.installations.$systemId'
import { Route as EngineeringInstallationsAssemblyRouteImport } from './routes/engineering.installations.assembly'
import { Route as EngineeringInstallationsFluidRouteImport } from './routes/engineering.installations.fluid'
import { Route as EngineeringInstallationsLimitsRouteImport } from './routes/engineering.installations.limits'
import { Route as EngineeringInstallationsWellRouteImport } from './routes/engineering.installations.well'
import { Route as EngineeringCatalogPumpsModelIdRouteImport } from './routes/engineering.catalog.pumps.$modelId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdministrationRoute = AdministrationRouteImport.update({
  id: '/administration',
  path: '/administration',
  getParentRoute: () => rootRouteImport,
} as any)
const AssetDefinitionRoute = AssetDefinitionRouteImport.update({
  id: '/asset-definition',
  path: '/asset-definition',
  getParentRoute: () => rootRouteImport,
} as any)
const AssetDefinitionsRoute = AssetDefinitionsRouteImport.update({
  id: '/asset-definitions',
  path: '/asset-definitions',
  getParentRoute: () => rootRouteImport,
} as any)
const DesignCasesRoute = DesignCasesRouteImport.update({
  id: '/design-cases',
  path: '/design-cases',
  getParentRoute: () => rootRouteImport,
} as any)
const EngineeringRoute = EngineeringRouteImport.update({
  id: '/engineering',
  path: '/engineering',
  getParentRoute: () => rootRouteImport,
} as any)
const ExceptionsRoute = ExceptionsRouteImport.update({
  id: '/exceptions',
  path: '/exceptions',
  getParentRoute: () => rootRouteImport,
} as any)
const ReliabilityRoute = ReliabilityRouteImport.update({
  id: '/reliability',
  path: '/reliability',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const TroubleshootingRoute = TroubleshootingRouteImport.update({
  id: '/troubleshooting',
  path: '/troubleshooting',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkbenchRoute = WorkbenchRouteImport.update({
  id: '/workbench',
  path: '/workbench',
  getParentRoute: () => rootRouteImport,
} as any)
const EngineeringIndexRoute = EngineeringIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EngineeringRoute,
} as any)
const EngineeringCatalogRoute = EngineeringCatalogRouteImport.update({
  id: '/catalog',
  path: '/catalog',
  getParentRoute: () => EngineeringRoute,
} as any)
const EngineeringDesignCasesRoute = EngineeringDesignCasesRouteImport.update({
  id: '/design-cases',
  path: '/design-cases',
  getParentRoute: () => EngineeringRoute,
} as any)
const EngineeringGovernanceRoute = EngineeringGovernanceRouteImport.update({
  id: '/governance',
  path: '/governance',
  getParentRoute: () => EngineeringRoute,
} as any)
const EngineeringInstallationsRoute =
  EngineeringInstallationsRouteImport.update({
    id: '/installations',
    path: '/installations',
    getParentRoute: () => EngineeringRoute,
  } as any)
const EngineeringWorkbenchRoute = EngineeringWorkbenchRouteImport.update({
  id: '/workbench',
  path: '/workbench',
  getParentRoute: () => EngineeringRoute,
} as any)
const WellsIndexRoute = WellsIndexRouteImport.update({
  id: '/wells/',
  path: '/wells/',
  getParentRoute: () => rootRouteImport,
} as any)
const WellsWellIdRoute = WellsWellIdRouteImport.update({
  id: '/wells/$wellId',
  path: '/wells/$wellId',
  getParentRoute: () => rootRouteImport,
} as any)
const EngineeringCatalogIndexRoute = EngineeringCatalogIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EngineeringCatalogRoute,
} as any)
const EngineeringDefinitionIndexRoute =
  EngineeringDefinitionIndexRouteImport.update({
    id: '/definition/',
    path: '/definition/',
    getParentRoute: () => EngineeringRoute,
  } as any)
const EngineeringDefinitionWellIdRoute =
  EngineeringDefinitionWellIdRouteImport.update({
    id: '/definition/$wellId',
    path: '/definition/$wellId',
    getParentRoute: () => EngineeringRoute,
  } as any)
const EngineeringGovernanceIndexRoute =
  EngineeringGovernanceIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => EngineeringGovernanceRoute,
  } as any)
const EngineeringGovernanceImportRoute =
  EngineeringGovernanceImportRouteImport.update({
    id: '/import',
    path: '/import',
    getParentRoute: () => EngineeringGovernanceRoute,
  } as any)
const EngineeringGovernanceQualityRoute =
  EngineeringGovernanceQualityRouteImport.update({
    id: '/quality',
    path: '/quality',
    getParentRoute: () => EngineeringGovernanceRoute,
  } as any)
const EngineeringGovernanceSourcesRoute =
  EngineeringGovernanceSourcesRouteImport.update({
    id: '/sources',
    path: '/sources',
    getParentRoute: () => EngineeringGovernanceRoute,
  } as any)
const EngineeringGovernanceValidationRoute =
  EngineeringGovernanceValidationRouteImport.update({
    id: '/validation',
    path: '/validation',
    getParentRoute: () => EngineeringGovernanceRoute,
  } as any)
const EngineeringInstallationsIndexRoute =
  EngineeringInstallationsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => EngineeringInstallationsRoute,
  } as any)
const EngineeringInstallationsSystemIdRoute =
  EngineeringInstallationsSystemIdRouteImport.update({
    id: '/$systemId',
    path: '/$systemId',
    getParentRoute: () => EngineeringInstallationsRoute,
  } as any)
const EngineeringInstallationsAssemblyRoute =
  EngineeringInstallationsAssemblyRouteImport.update({
    id: '/assembly',
    path: '/assembly',
    getParentRoute: () => EngineeringInstallationsRoute,
  } as any)
const EngineeringInstallationsFluidRoute =
  EngineeringInstallationsFluidRouteImport.update({
    id: '/fluid',
    path: '/fluid',
    getParentRoute: () => EngineeringInstallationsRoute,
  } as any)
const EngineeringInstallationsLimitsRoute =
  EngineeringInstallationsLimitsRouteImport.update({
    id: '/limits',
    path: '/limits',
    getParentRoute: () => EngineeringInstallationsRoute,
  } as any)
const EngineeringInstallationsWellRoute =
  EngineeringInstallationsWellRouteImport.update({
    id: '/well',
    path: '/well',
    getParentRoute: () => EngineeringInstallationsRoute,
  } as any)
const EngineeringCatalogPumpsModelIdRoute =
  EngineeringCatalogPumpsModelIdRouteImport.update({
    id: '/pumps/$modelId',
    path: '/pumps/$modelId',
    getParentRoute: () => EngineeringCatalogRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/administration': typeof AdministrationRoute
  '/asset-definition': typeof AssetDefinitionRoute
  '/asset-definitions': typeof AssetDefinitionsRoute
  '/design-cases': typeof DesignCasesRoute
  '/engineering': typeof EngineeringRouteWithChildren
  '/exceptions': typeof ExceptionsRoute
  '/reliability': typeof ReliabilityRoute
  '/reports': typeof ReportsRoute
  '/troubleshooting': typeof TroubleshootingRoute
  '/workbench': typeof WorkbenchRoute
  '/engineering/catalog': typeof EngineeringCatalogRouteWithChildren
  '/engineering/design-cases': typeof EngineeringDesignCasesRoute
  '/engineering/governance': typeof EngineeringGovernanceRouteWithChildren
  '/engineering/installations': typeof EngineeringInstallationsRouteWithChildren
  '/engineering/workbench': typeof EngineeringWorkbenchRoute
  '/wells/$wellId': typeof WellsWellIdRoute
  '/engineering/': typeof EngineeringIndexRoute
  '/wells/': typeof WellsIndexRoute
  '/engineering/definition/$wellId': typeof EngineeringDefinitionWellIdRoute
  '/engineering/governance/import': typeof EngineeringGovernanceImportRoute
  '/engineering/governance/quality': typeof EngineeringGovernanceQualityRoute
  '/engineering/governance/sources': typeof EngineeringGovernanceSourcesRoute
  '/engineering/governance/validation': typeof EngineeringGovernanceValidationRoute
  '/engineering/installations/$systemId': typeof EngineeringInstallationsSystemIdRoute
  '/engineering/installations/assembly': typeof EngineeringInstallationsAssemblyRoute
  '/engineering/installations/fluid': typeof EngineeringInstallationsFluidRoute
  '/engineering/installations/limits': typeof EngineeringInstallationsLimitsRoute
  '/engineering/installations/well': typeof EngineeringInstallationsWellRoute
  '/engineering/catalog/': typeof EngineeringCatalogIndexRoute
  '/engineering/definition/': typeof EngineeringDefinitionIndexRoute
  '/engineering/governance/': typeof EngineeringGovernanceIndexRoute
  '/engineering/installations/': typeof EngineeringInstallationsIndexRoute
  '/engineering/catalog/pumps/$modelId': typeof EngineeringCatalogPumpsModelIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/administration': typeof AdministrationRoute
  '/asset-definition': typeof AssetDefinitionRoute
  '/asset-definitions': typeof AssetDefinitionsRoute
  '/design-cases': typeof DesignCasesRoute
  '/exceptions': typeof ExceptionsRoute
  '/reliability': typeof ReliabilityRoute
  '/reports': typeof ReportsRoute
  '/troubleshooting': typeof TroubleshootingRoute
  '/workbench': typeof WorkbenchRoute
  '/engineering/design-cases': typeof EngineeringDesignCasesRoute
  '/engineering/workbench': typeof EngineeringWorkbenchRoute
  '/wells/$wellId': typeof WellsWellIdRoute
  '/engineering': typeof EngineeringIndexRoute
  '/wells': typeof WellsIndexRoute
  '/engineering/definition/$wellId': typeof EngineeringDefinitionWellIdRoute
  '/engineering/governance/import': typeof EngineeringGovernanceImportRoute
  '/engineering/governance/quality': typeof EngineeringGovernanceQualityRoute
  '/engineering/governance/sources': typeof EngineeringGovernanceSourcesRoute
  '/engineering/governance/validation': typeof EngineeringGovernanceValidationRoute
  '/engineering/installations/$systemId': typeof EngineeringInstallationsSystemIdRoute
  '/engineering/installations/assembly': typeof EngineeringInstallationsAssemblyRoute
  '/engineering/installations/fluid': typeof EngineeringInstallationsFluidRoute
  '/engineering/installations/limits': typeof EngineeringInstallationsLimitsRoute
  '/engineering/installations/well': typeof EngineeringInstallationsWellRoute
  '/engineering/catalog': typeof EngineeringCatalogIndexRoute
  '/engineering/definition': typeof EngineeringDefinitionIndexRoute
  '/engineering/governance': typeof EngineeringGovernanceIndexRoute
  '/engineering/installations': typeof EngineeringInstallationsIndexRoute
  '/engineering/catalog/pumps/$modelId': typeof EngineeringCatalogPumpsModelIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/administration': typeof AdministrationRoute
  '/asset-definition': typeof AssetDefinitionRoute
  '/asset-definitions': typeof AssetDefinitionsRoute
  '/design-cases': typeof DesignCasesRoute
  '/engineering': typeof EngineeringRouteWithChildren
  '/exceptions': typeof ExceptionsRoute
  '/reliability': typeof ReliabilityRoute
  '/reports': typeof ReportsRoute
  '/troubleshooting': typeof TroubleshootingRoute
  '/workbench': typeof WorkbenchRoute
  '/engineering/catalog': typeof EngineeringCatalogRouteWithChildren
  '/engineering/design-cases': typeof EngineeringDesignCasesRoute
  '/engineering/governance': typeof EngineeringGovernanceRouteWithChildren
  '/engineering/installations': typeof EngineeringInstallationsRouteWithChildren
  '/engineering/workbench': typeof EngineeringWorkbenchRoute
  '/wells/$wellId': typeof WellsWellIdRoute
  '/engineering/': typeof EngineeringIndexRoute
  '/wells/': typeof WellsIndexRoute
  '/engineering/definition/$wellId': typeof EngineeringDefinitionWellIdRoute
  '/engineering/governance/import': typeof EngineeringGovernanceImportRoute
  '/engineering/governance/quality': typeof EngineeringGovernanceQualityRoute
  '/engineering/governance/sources': typeof EngineeringGovernanceSourcesRoute
  '/engineering/governance/validation': typeof EngineeringGovernanceValidationRoute
  '/engineering/installations/$systemId': typeof EngineeringInstallationsSystemIdRoute
  '/engineering/installations/assembly': typeof EngineeringInstallationsAssemblyRoute
  '/engineering/installations/fluid': typeof EngineeringInstallationsFluidRoute
  '/engineering/installations/limits': typeof EngineeringInstallationsLimitsRoute
  '/engineering/installations/well': typeof EngineeringInstallationsWellRoute
  '/engineering/catalog/': typeof EngineeringCatalogIndexRoute
  '/engineering/definition/': typeof EngineeringDefinitionIndexRoute
  '/engineering/governance/': typeof EngineeringGovernanceIndexRoute
  '/engineering/installations/': typeof EngineeringInstallationsIndexRoute
  '/engineering/catalog/pumps/$modelId': typeof EngineeringCatalogPumpsModelIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/administration'
    | '/asset-definition'
    | '/asset-definitions'
    | '/design-cases'
    | '/engineering'
    | '/exceptions'
    | '/reliability'
    | '/reports'
    | '/troubleshooting'
    | '/workbench'
    | '/engineering/catalog'
    | '/engineering/design-cases'
    | '/engineering/governance'
    | '/engineering/installations'
    | '/engineering/workbench'
    | '/wells/$wellId'
    | '/engineering/'
    | '/wells/'
    | '/engineering/definition/$wellId'
    | '/engineering/governance/import'
    | '/engineering/governance/quality'
    | '/engineering/governance/sources'
    | '/engineering/governance/validation'
    | '/engineering/installations/$systemId'
    | '/engineering/installations/assembly'
    | '/engineering/installations/fluid'
    | '/engineering/installations/limits'
    | '/engineering/installations/well'
    | '/engineering/catalog/'
    | '/engineering/definition/'
    | '/engineering/governance/'
    | '/engineering/installations/'
    | '/engineering/catalog/pumps/$modelId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/administration'
    | '/asset-definition'
    | '/asset-definitions'
    | '/design-cases'
    | '/exceptions'
    | '/reliability'
    | '/reports'
    | '/troubleshooting'
    | '/workbench'
    | '/engineering/design-cases'
    | '/engineering/workbench'
    | '/wells/$wellId'
    | '/engineering'
    | '/wells'
    | '/engineering/definition/$wellId'
    | '/engineering/governance/import'
    | '/engineering/governance/quality'
    | '/engineering/governance/sources'
    | '/engineering/governance/validation'
    | '/engineering/installations/$systemId'
    | '/engineering/installations/assembly'
    | '/engineering/installations/fluid'
    | '/engineering/installations/limits'
    | '/engineering/installations/well'
    | '/engineering/catalog'
    | '/engineering/definition'
    | '/engineering/governance'
    | '/engineering/installations'
    | '/engineering/catalog/pumps/$modelId'
  id:
    | '__root__'
    | '/'
    | '/administration'
    | '/asset-definition'
    | '/asset-definitions'
    | '/design-cases'
    | '/engineering'
    | '/exceptions'
    | '/reliability'
    | '/reports'
    | '/troubleshooting'
    | '/workbench'
    | '/engineering/catalog'
    | '/engineering/design-cases'
    | '/engineering/governance'
    | '/engineering/installations'
    | '/engineering/workbench'
    | '/wells/$wellId'
    | '/engineering/'
    | '/wells/'
    | '/engineering/definition/$wellId'
    | '/engineering/governance/import'
    | '/engineering/governance/quality'
    | '/engineering/governance/sources'
    | '/engineering/governance/validation'
    | '/engineering/installations/$systemId'
    | '/engineering/installations/assembly'
    | '/engineering/installations/fluid'
    | '/engineering/installations/limits'
    | '/engineering/installations/well'
    | '/engineering/catalog/'
    | '/engineering/definition/'
    | '/engineering/governance/'
    | '/engineering/installations/'
    | '/engineering/catalog/pumps/$modelId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdministrationRoute: typeof AdministrationRoute
  AssetDefinitionRoute: typeof AssetDefinitionRoute
  AssetDefinitionsRoute: typeof AssetDefinitionsRoute
  DesignCasesRoute: typeof DesignCasesRoute
  EngineeringRoute: typeof EngineeringRouteWithChildren
  ExceptionsRoute: typeof ExceptionsRoute
  ReliabilityRoute: typeof ReliabilityRoute
  ReportsRoute: typeof ReportsRoute
  TroubleshootingRoute: typeof TroubleshootingRoute
  WorkbenchRoute: typeof WorkbenchRoute
  WellsWellIdRoute: typeof WellsWellIdRoute
  WellsIndexRoute: typeof WellsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/administration': {
      id: '/administration'
      path: '/administration'
      fullPath: '/administration'
      preLoaderRoute: typeof AdministrationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/asset-definition': {
      id: '/asset-definition'
      path: '/asset-definition'
      fullPath: '/asset-definition'
      preLoaderRoute: typeof AssetDefinitionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/asset-definitions': {
      id: '/asset-definitions'
      path: '/asset-definitions'
      fullPath: '/asset-definitions'
      preLoaderRoute: typeof AssetDefinitionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/design-cases': {
      id: '/design-cases'
      path: '/design-cases'
      fullPath: '/design-cases'
      preLoaderRoute: typeof DesignCasesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/engineering': {
      id: '/engineering'
      path: '/engineering'
      fullPath: '/engineering'
      preLoaderRoute: typeof EngineeringRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exceptions': {
      id: '/exceptions'
      path: '/exceptions'
      fullPath: '/exceptions'
      preLoaderRoute: typeof ExceptionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reliability': {
      id: '/reliability'
      path: '/reliability'
      fullPath: '/reliability'
      preLoaderRoute: typeof ReliabilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/troubleshooting': {
      id: '/troubleshooting'
      path: '/troubleshooting'
      fullPath: '/troubleshooting'
      preLoaderRoute: typeof TroubleshootingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workbench': {
      id: '/workbench'
      path: '/workbench'
      fullPath: '/workbench'
      preLoaderRoute: typeof WorkbenchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/engineering/': {
      id: '/engineering/'
      path: '/'
      fullPath: '/engineering/'
      preLoaderRoute: typeof EngineeringIndexRouteImport
      parentRoute: typeof EngineeringRoute
    }
    '/engineering/catalog': {
      id: '/engineering/catalog'
      path: '/catalog'
      fullPath: '/engineering/catalog'
      preLoaderRoute: typeof EngineeringCatalogRouteImport
      parentRoute: typeof EngineeringRoute
    }
    '/engineering/design-cases': {
      id: '/engineering/design-cases'
      path: '/design-cases'
      fullPath: '/engineering/design-cases'
      preLoaderRoute: typeof EngineeringDesignCasesRouteImport
      parentRoute: typeof EngineeringRoute
    }
    '/engineering/governance': {
      id: '/engineering/governance'
      path: '/governance'
      fullPath: '/engineering/governance'
      preLoaderRoute: typeof EngineeringGovernanceRouteImport
      parentRoute: typeof EngineeringRoute
    }
    '/engineering/installations': {
      id: '/engineering/installations'
      path: '/installations'
      fullPath: '/engineering/installations'
      preLoaderRoute: typeof EngineeringInstallationsRouteImport
      parentRoute: typeof EngineeringRoute
    }
    '/engineering/workbench': {
      id: '/engineering/workbench'
      path: '/workbench'
      fullPath: '/engineering/workbench'
      preLoaderRoute: typeof EngineeringWorkbenchRouteImport
      parentRoute: typeof EngineeringRoute
    }
    '/wells/': {
      id: '/wells/'
      path: '/wells'
      fullPath: '/wells/'
      preLoaderRoute: typeof WellsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wells/$wellId': {
      id: '/wells/$wellId'
      path: '/wells/$wellId'
      fullPath: '/wells/$wellId'
      preLoaderRoute: typeof WellsWellIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/engineering/catalog/': {
      id: '/engineering/catalog/'
      path: '/'
      fullPath: '/engineering/catalog/'
      preLoaderRoute: typeof EngineeringCatalogIndexRouteImport
      parentRoute: typeof EngineeringCatalogRoute
    }
    '/engineering/definition/': {
      id: '/engineering/definition/'
      path: '/definition'
      fullPath: '/engineering/definition/'
      preLoaderRoute: typeof EngineeringDefinitionIndexRouteImport
      parentRoute: typeof EngineeringRoute
    }
    '/engineering/definition/$wellId': {
      id: '/engineering/definition/$wellId'
      path: '/definition/$wellId'
      fullPath: '/engineering/definition/$wellId'
      preLoaderRoute: typeof EngineeringDefinitionWellIdRouteImport
      parentRoute: typeof EngineeringRoute
    }
    '/engineering/governance/': {
      id: '/engineering/governance/'
      path: '/'
      fullPath: '/engineering/governance/'
      preLoaderRoute: typeof EngineeringGovernanceIndexRouteImport
      parentRoute: typeof EngineeringGovernanceRoute
    }
    '/engineering/governance/import': {
      id: '/engineering/governance/import'
      path: '/import'
      fullPath: '/engineering/governance/import'
      preLoaderRoute: typeof EngineeringGovernanceImportRouteImport
      parentRoute: typeof EngineeringGovernanceRoute
    }
    '/engineering/governance/quality': {
      id: '/engineering/governance/quality'
      path: '/quality'
      fullPath: '/engineering/governance/quality'
      preLoaderRoute: typeof EngineeringGovernanceQualityRouteImport
      parentRoute: typeof EngineeringGovernanceRoute
    }
    '/engineering/governance/sources': {
      id: '/engineering/governance/sources'
      path: '/sources'
      fullPath: '/engineering/governance/sources'
      preLoaderRoute: typeof EngineeringGovernanceSourcesRouteImport
      parentRoute: typeof EngineeringGovernanceRoute
    }
    '/engineering/governance/validation': {
      id: '/engineering/governance/validation'
      path: '/validation'
      fullPath: '/engineering/governance/validation'
      preLoaderRoute: typeof EngineeringGovernanceValidationRouteImport
      parentRoute: typeof EngineeringGovernanceRoute
    }
    '/engineering/installations/': {
      id: '/engineering/installations/'
      path: '/'
      fullPath: '/engineering/installations/'
      preLoaderRoute: typeof EngineeringInstallationsIndexRouteImport
      parentRoute: typeof EngineeringInstallationsRoute
    }
    '/engineering/installations/$systemId': {
      id: '/engineering/installations/$systemId'
      path: '/$systemId'
      fullPath: '/engineering/installations/$systemId'
      preLoaderRoute: typeof EngineeringInstallationsSystemIdRouteImport
      parentRoute: typeof EngineeringInstallationsRoute
    }
    '/engineering/installations/assembly': {
      id: '/engineering/installations/assembly'
      path: '/assembly'
      fullPath: '/engineering/installations/assembly'
      preLoaderRoute: typeof EngineeringInstallationsAssemblyRouteImport
      parentRoute: typeof EngineeringInstallationsRoute
    }
    '/engineering/installations/fluid': {
      id: '/engineering/installations/fluid'
      path: '/fluid'
      fullPath: '/engineering/installations/fluid'
      preLoaderRoute: typeof EngineeringInstallationsFluidRouteImport
      parentRoute: typeof EngineeringInstallationsRoute
    }
    '/engineering/installations/limits': {
      id: '/engineering/installations/limits'
      path: '/limits'
      fullPath: '/engineering/installations/limits'
      preLoaderRoute: typeof EngineeringInstallationsLimitsRouteImport
      parentRoute: typeof EngineeringInstallationsRoute
    }
    '/engineering/installations/well': {
      id: '/engineering/installations/well'
      path: '/well'
      fullPath: '/engineering/installations/well'
      preLoaderRoute: typeof EngineeringInstallationsWellRouteImport
      parentRoute: typeof EngineeringInstallationsRoute
    }
    '/engineering/catalog/pumps/$modelId': {
      id: '/engineering/catalog/pumps/$modelId'
      path: '/pumps/$modelId'
      fullPath: '/engineering/catalog/pumps/$modelId'
      preLoaderRoute: typeof EngineeringCatalogPumpsModelIdRouteImport
      parentRoute: typeof EngineeringCatalogRoute
    }
  }
}

interface EngineeringCatalogRouteChildren {
  EngineeringCatalogIndexRoute: typeof EngineeringCatalogIndexRoute
  EngineeringCatalogPumpsModelIdRoute: typeof EngineeringCatalogPumpsModelIdRoute
}

const EngineeringCatalogRouteChildren: EngineeringCatalogRouteChildren = {
  EngineeringCatalogIndexRoute: EngineeringCatalogIndexRoute,
  EngineeringCatalogPumpsModelIdRoute: EngineeringCatalogPumpsModelIdRoute,
}

const EngineeringCatalogRouteWithChildren =
  EngineeringCatalogRoute._addFileChildren(EngineeringCatalogRouteChildren)

interface EngineeringGovernanceRouteChildren {
  EngineeringGovernanceImportRoute: typeof EngineeringGovernanceImportRoute
  EngineeringGovernanceQualityRoute: typeof EngineeringGovernanceQualityRoute
  EngineeringGovernanceSourcesRoute: typeof EngineeringGovernanceSourcesRoute
  EngineeringGovernanceValidationRoute: typeof EngineeringGovernanceValidationRoute
  EngineeringGovernanceIndexRoute: typeof EngineeringGovernanceIndexRoute
}

const EngineeringGovernanceRouteChildren: EngineeringGovernanceRouteChildren = {
  EngineeringGovernanceImportRoute: EngineeringGovernanceImportRoute,
  EngineeringGovernanceQualityRoute: EngineeringGovernanceQualityRoute,
  EngineeringGovernanceSourcesRoute: EngineeringGovernanceSourcesRoute,
  EngineeringGovernanceValidationRoute: EngineeringGovernanceValidationRoute,
  EngineeringGovernanceIndexRoute: EngineeringGovernanceIndexRoute,
}

const EngineeringGovernanceRouteWithChildren =
  EngineeringGovernanceRoute._addFileChildren(
    EngineeringGovernanceRouteChildren,
  )

interface EngineeringInstallationsRouteChildren {
  EngineeringInstallationsSystemIdRoute: typeof EngineeringInstallationsSystemIdRoute
  EngineeringInstallationsAssemblyRoute: typeof EngineeringInstallationsAssemblyRoute
  EngineeringInstallationsFluidRoute: typeof EngineeringInstallationsFluidRoute
  EngineeringInstallationsLimitsRoute: typeof EngineeringInstallationsLimitsRoute
  EngineeringInstallationsWellRoute: typeof EngineeringInstallationsWellRoute
  EngineeringInstallationsIndexRoute: typeof EngineeringInstallationsIndexRoute
}

const EngineeringInstallationsRouteChildren: EngineeringInstallationsRouteChildren =
  {
    EngineeringInstallationsSystemIdRoute:
      EngineeringInstallationsSystemIdRoute,
    EngineeringInstallationsAssemblyRoute:
      EngineeringInstallationsAssemblyRoute,
    EngineeringInstallationsFluidRoute: EngineeringInstallationsFluidRoute,
    EngineeringInstallationsLimitsRoute: EngineeringInstallationsLimitsRoute,
    EngineeringInstallationsWellRoute: EngineeringInstallationsWellRoute,
    EngineeringInstallationsIndexRoute: EngineeringInstallationsIndexRoute,
  }

const EngineeringInstallationsRouteWithChildren =
  EngineeringInstallationsRoute._addFileChildren(
    EngineeringInstallationsRouteChildren,
  )

interface EngineeringRouteChildren {
  EngineeringCatalogRoute: typeof EngineeringCatalogRouteWithChildren
  EngineeringDesignCasesRoute: typeof EngineeringDesignCasesRoute
  EngineeringGovernanceRoute: typeof EngineeringGovernanceRouteWithChildren
  EngineeringInstallationsRoute: typeof EngineeringInstallationsRouteWithChildren
  EngineeringWorkbenchRoute: typeof EngineeringWorkbenchRoute
  EngineeringIndexRoute: typeof EngineeringIndexRoute
  EngineeringDefinitionWellIdRoute: typeof EngineeringDefinitionWellIdRoute
  EngineeringDefinitionIndexRoute: typeof EngineeringDefinitionIndexRoute
}

const EngineeringRouteChildren: EngineeringRouteChildren = {
  EngineeringCatalogRoute: EngineeringCatalogRouteWithChildren,
  EngineeringDesignCasesRoute: EngineeringDesignCasesRoute,
  EngineeringGovernanceRoute: EngineeringGovernanceRouteWithChildren,
  EngineeringInstallationsRoute: EngineeringInstallationsRouteWithChildren,
  EngineeringWorkbenchRoute: EngineeringWorkbenchRoute,
  EngineeringIndexRoute: EngineeringIndexRoute,
  EngineeringDefinitionWellIdRoute: EngineeringDefinitionWellIdRoute,
  EngineeringDefinitionIndexRoute: EngineeringDefinitionIndexRoute,
}

const EngineeringRouteWithChildren = EngineeringRoute._addFileChildren(
  EngineeringRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdministrationRoute: AdministrationRoute,
  AssetDefinitionRoute: AssetDefinitionRoute,
  AssetDefinitionsRoute: AssetDefinitionsRoute,
  DesignCasesRoute: DesignCasesRoute,
  EngineeringRoute: EngineeringRouteWithChildren,
  ExceptionsRoute: ExceptionsRoute,
  ReliabilityRoute: ReliabilityRoute,
  ReportsRoute: ReportsRoute,
  TroubleshootingRoute: TroubleshootingRoute,
  WorkbenchRoute: WorkbenchRoute,
  WellsWellIdRoute: WellsWellIdRoute,
  WellsIndexRoute: WellsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
