from typing import AsyncGenerator, Optional, Union
from app.contracts.advisory import Advisory
from app.contracts.enums import FrameType, Route
from app.contracts.events import (
    AdvisoryFrame,
    ClarificationFrame,
    DoneFrame,
    ErrorFrame,
    Frame,
    InterruptFrame,
    StatusFrame,
    TextDeltaFrame,
    VisualFrame,
)
from app.contracts.visualization import VisualizationSpec


class ResponseAssembler:
    """
    Single terminal stage for every route.
    Yields NDJSON formatted strings ending in a done frame.
    Supports AdvisoryFrame and VisualFrame for WORKFLOW routes.
    """

    @staticmethod
    async def assemble_stream(
        run_id: str,
        route: Route,
        text: Optional[str] = None,
        clarification: Optional[ClarificationFrame] = None,
        interrupt: Optional[InterruptFrame] = None,
        error: Optional[ErrorFrame] = None,
        advisory: Optional[Union[Advisory, dict]] = None,
        visualization: Optional[Union[VisualizationSpec, dict]] = None,
        status_notes: Optional[list[str]] = None,
        llm_available: bool = True,
        done_status: Optional[str] = None,
    ) -> AsyncGenerator[str, None]:
        # 0. Flag LLM outage up front if unavailable
        if not llm_available:
            yield StatusFrame(
                run_id=run_id,
                stage="llm_gateway",
                progress=0,
                message="LLM gateway unavailable — response generated by deterministic fallback, not the model.",
            ).model_dump_json() + "\n"

        # 0.1 Optional status notes (e.g. data source health)
        if status_notes:
            for note in status_notes:
                yield StatusFrame(
                    run_id=run_id,
                    stage="evidence_gateway",
                    progress=100,
                    message=note,
                ).model_dump_json() + "\n"

        # 1. Error Frame if explicitly provided
        if error:
            yield error.model_dump_json() + "\n"
            status = done_status or ("INSUFFICIENT" if error.code == "INSUFFICIENT_EVIDENCE" else "ERROR")
            yield DoneFrame(run_id=run_id, status=status).model_dump_json() + "\n"
            return

        # 2. Clarification Frame (CLARIFY path)
        if clarification:
            yield clarification.model_dump_json() + "\n"
            yield DoneFrame(run_id=run_id, status=done_status or "PAUSED").model_dump_json() + "\n"
            return

        # 3. Interrupt Frame (APPROVE path)
        if interrupt:
            yield interrupt.model_dump_json() + "\n"
            yield DoneFrame(run_id=run_id, status=done_status or "PAUSED").model_dump_json() + "\n"
            return

        # 4. Advisory Frame (WORKFLOW diagnostic outcome)
        if advisory:
            source_refs = []
            if isinstance(advisory, Advisory):
                source_refs = list(dict.fromkeys(advisory.cited_evidence_ids))
                adv_dict = advisory.model_dump()
            elif isinstance(advisory, dict):
                source_refs = list(dict.fromkeys(advisory.get("cited_evidence_ids", [])))
                adv_dict = advisory
            else:
                adv_dict = {}
            yield AdvisoryFrame(
                run_id=run_id,
                advisory=adv_dict,
                source_refs=source_refs,
            ).model_dump_json() + "\n"

        # 5. Visual Frame (WORKFLOW cards selection)
        if visualization and route != "SIMPLE":
            has_cards = False
            if isinstance(visualization, VisualizationSpec):
                has_cards = bool(visualization.card_ids)
                viz_dict = visualization.model_dump()
            elif isinstance(visualization, dict):
                has_cards = bool(visualization.get("card_ids") or visualization.get("cards"))
                viz_dict = visualization
            else:
                viz_dict = {}
            if has_cards:
                yield VisualFrame(
                    run_id=run_id,
                    visualization=viz_dict,
                ).model_dump_json() + "\n"

        # 6. Text Output (SIMPLE or WORKFLOW/FOLLOW_UP text)
        if text is None or not text.strip():
            # If advisory or visual frame was sent, empty text is acceptable; otherwise error
            if advisory or visualization:
                yield DoneFrame(run_id=run_id, status=done_status or "OK").model_dump_json() + "\n"
                return
            err = ErrorFrame(
                run_id=run_id,
                code="EMPTY_LLM_OUTPUT",
                message="I couldn't produce a clear answer. Could you please rephrase?",
            )
            yield err.model_dump_json() + "\n"
            yield DoneFrame(run_id=run_id, status=done_status or "ERROR").model_dump_json() + "\n"
            return

        # Stream text in delta frame
        yield TextDeltaFrame(run_id=run_id, delta=text).model_dump_json() + "\n"
        yield DoneFrame(run_id=run_id, status=done_status or "OK").model_dump_json() + "\n"
